# Generated by Django 5.1.1 on 2024-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0003_dropdownoption_violationtype_course_section_signup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='registration_cert',
            field=models.FileField(upload_to='registration_certs/', verbose_name='Certificate of Registration (COR)'),
        ),
    ]
