# Generated by Django 5.1.1 on 2024-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0004_remove_user_employee_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('On Hold', 'Minor'), ('Active', 'Major'), ('Resolved', 'Major'), ('Deny', 'Major')], default='On Hold', max_length=10),
        ),
    ]
