# Generated by Django 5.1.1 on 2024-11-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0005_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationtype',
            name='sanction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
