# Generated by Django 5.1.1 on 2024-11-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0006_violationtype_sanction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('Active', 'Active'), ('Resolved', 'Resolved'), ('Deny', 'Deny')], default='On Hold', max_length=10),
        ),
    ]
