# Generated by Django 5.1.1 on 2024-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0008_userrole_guard_student_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationtype',
            name='sanction_period_type',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], max_length=10),
        ),
    ]
