# Generated by Django 5.1.1 on 2024-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0009_alter_violationtype_sanction_period_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='program1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.RemoveField(
            model_name='report',
            name='violation_type',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='section',
        ),
        migrations.DeleteModel(
            name='Userrole',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('GUARD', 'Guard')], default='STUDENT', max_length=50),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='DropdownOption',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ViolationType',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
