# Generated by Django 5.1.1 on 2024-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0009_alter_violationtype_sanction_period_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('idnumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('program1', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('id_picture', models.FileField(blank=True, null=True, upload_to='approved_id_pictures/')),
                ('registration_cert', models.FileField(blank=True, null=True, upload_to='approved_registration_certs/')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('idnumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('program1', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('id_picture', models.FileField(blank=True, null=True, upload_to='rejected_id_pictures/')),
                ('registration_cert', models.FileField(blank=True, null=True, upload_to='rejected_registration_certs/')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
