# Generated by Django 5.1.1 on 2024-11-11 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0010_remove_course_program_remove_signup_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_image', models.ImageField(blank=True, null=True, upload_to='student_documents/cor/')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='student_documents/id/')),
                ('is_approved', models.BooleanField(default=False)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
