# Generated by Django 5.1.1 on 2024-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0012_alter_studentregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
