# Generated by Django 5.1.1 on 2024-11-29 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0015_program_alter_studentregistration_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='adminmod.student')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('imposed_date', models.DateField(default=django.utils.timezone.now)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanction', to='adminmod.violation')),
            ],
        ),
    ]
