# Generated by Django 5.1.1 on 2024-11-29 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0017_remove_violation_student_delete_sanction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'ordering': ['severity_level', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='adminmod.violation')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['violation', 'name'],
                'unique_together': {('violation', 'name')},
            },
        ),
    ]
