# Generated by Django 5.1.1 on 2024-11-29 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0018_violation_alter_program_options_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='corresponding_penalty',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='prohibited_act',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
