# Generated by Django 5.1.1 on 2024-11-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0019_violation_corresponding_penalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanction',
            name='description',
        ),
    ]
