# Generated by Django 5.1.1 on 2024-11-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0020_remove_sanction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='description',
        ),
    ]
