# Generated by Django 5.1.1 on 2024-11-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0021_remove_violation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='duration_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='duration',
            field=models.IntegerField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')]),
        ),
        migrations.AlterField(
            model_name='violation',
            name='corresponding_penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_violations', to='adminmod.sanction'),
        ),
    ]
