# Generated by Django 5.1.1 on 2024-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0022_sanction_duration_value_alter_sanction_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='duration',
        ),
        migrations.AddField(
            model_name='sanction',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=10),
        ),
    ]
