# Generated by Django 5.1.1 on 2024-11-29 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0023_remove_sanction_created_at_remove_sanction_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
