# Generated by Django 5.1.1 on 2024-11-30 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0024_sanction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'code')},
        ),
    ]
