# Generated by Django 5.1.1 on 2024-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0027_violationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
