# Generated by Django 5.1.1 on 2024-12-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0028_user_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrecord',
            name='sanction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminmod.sanction'),
        ),
    ]
