# Generated by Django 5.1.1 on 2025-01-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0029_violationrecord_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrecord',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='total_hours_complied',
            field=models.FloatField(default=0.0),
        ),
    ]
