# Generated by Django 5.1.1 on 2025-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0030_violationrecord_qr_code_violationrecord_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
