# Generated by Django 5.1.1 on 2025-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmod', '0031_studentregistration_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='duration_unit',
            field=models.CharField(choices=[('hour', 'Hour'), ('hours', 'Hours')], default='hours', max_length=10),
        ),
    ]
